# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Xilinx/Projects/UART/UART.srcs/sources_1/bd/myDesign/ip/myDesign_microblaze_0_0/myDesign_microblaze_0_0.xci
# IP: The module: 'myDesign_microblaze_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Xilinx/Projects/UART/UART.gen/sources_1/bd/myDesign/ip/myDesign_microblaze_0_0/myDesign_microblaze_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'myDesign_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Xilinx/Projects/UART/UART.gen/sources_1/bd/myDesign/ip/myDesign_microblaze_0_0/myDesign_microblaze_0_0_ooc_debug.xdc
# XDC: The top module name and the constraint reference have the same name: 'myDesign_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Xilinx/Projects/UART/UART.gen/sources_1/bd/myDesign/ip/myDesign_microblaze_0_0/myDesign_microblaze_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'myDesign_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/Xilinx/Projects/UART/UART.srcs/sources_1/bd/myDesign/ip/myDesign_microblaze_0_0/myDesign_microblaze_0_0.xci
# IP: The module: 'myDesign_microblaze_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Xilinx/Projects/UART/UART.gen/sources_1/bd/myDesign/ip/myDesign_microblaze_0_0/myDesign_microblaze_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'myDesign_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Xilinx/Projects/UART/UART.gen/sources_1/bd/myDesign/ip/myDesign_microblaze_0_0/myDesign_microblaze_0_0_ooc_debug.xdc
# XDC: The top module name and the constraint reference have the same name: 'myDesign_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Xilinx/Projects/UART/UART.gen/sources_1/bd/myDesign/ip/myDesign_microblaze_0_0/myDesign_microblaze_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'myDesign_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
