# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/itspa/Downloads/Basys-3-Master.xdc

# Block Designs: bd/myDesign/myDesign.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==myDesign || ORIG_REF_NAME==myDesign} -quiet] -quiet

# IP: bd/myDesign/ip/myDesign_microblaze_0_0/myDesign_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==myDesign_microblaze_0_0 || ORIG_REF_NAME==myDesign_microblaze_0_0} -quiet] -quiet

# IP: bd/myDesign/ip/myDesign_axi_uartlite_0_0/myDesign_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==myDesign_axi_uartlite_0_0 || ORIG_REF_NAME==myDesign_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/myDesign/ip/myDesign_axi_interconnect_0_imp_xbar_0/myDesign_axi_interconnect_0_imp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==myDesign_axi_interconnect_0_imp_xbar_0 || ORIG_REF_NAME==myDesign_axi_interconnect_0_imp_xbar_0} -quiet] -quiet

# IP: bd/myDesign/ip/myDesign_axi_interconnect_0_0/myDesign_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==myDesign_axi_interconnect_0_0 || ORIG_REF_NAME==myDesign_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/myDesign/ip/myDesign_clk_wiz_0_0/myDesign_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==myDesign_clk_wiz_0_0 || ORIG_REF_NAME==myDesign_clk_wiz_0_0} -quiet] -quiet

# IP: bd/myDesign/ip/myDesign_proc_sys_reset_0_0/myDesign_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==myDesign_proc_sys_reset_0_0 || ORIG_REF_NAME==myDesign_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/myDesign/ip/myDesign_dlmb_v10_0/myDesign_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==myDesign_dlmb_v10_0 || ORIG_REF_NAME==myDesign_dlmb_v10_0} -quiet] -quiet

# IP: bd/myDesign/ip/myDesign_ilmb_v10_0/myDesign_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==myDesign_ilmb_v10_0 || ORIG_REF_NAME==myDesign_ilmb_v10_0} -quiet] -quiet

# IP: bd/myDesign/ip/myDesign_dlmb_bram_if_cntlr_0/myDesign_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==myDesign_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==myDesign_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/myDesign/ip/myDesign_ilmb_bram_if_cntlr_0/myDesign_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==myDesign_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==myDesign_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/myDesign/ip/myDesign_lmb_bram_0/myDesign_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==myDesign_lmb_bram_0 || ORIG_REF_NAME==myDesign_lmb_bram_0} -quiet] -quiet

# IP: bd/myDesign/ip/myDesign_mdm_1_0/myDesign_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==myDesign_mdm_1_0 || ORIG_REF_NAME==myDesign_mdm_1_0} -quiet] -quiet

# XDC: d:/Xilinx/Projects/UART/UART.gen/sources_1/bd/myDesign/myDesign_ooc.xdc
