# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Xilinx/Projects/UART/UART.srcs/sources_1/bd/myDesign/ip/myDesign_axi_interconnect_0_imp_xbar_0/myDesign_axi_interconnect_0_imp_xbar_0.xci
# IP: The module: 'myDesign_axi_interconnect_0_imp_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Xilinx/Projects/UART/UART.gen/sources_1/bd/myDesign/ip/myDesign_axi_interconnect_0_imp_xbar_0/myDesign_axi_interconnect_0_imp_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'myDesign_axi_interconnect_0_imp_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/Xilinx/Projects/UART/UART.srcs/sources_1/bd/myDesign/ip/myDesign_axi_interconnect_0_imp_xbar_0/myDesign_axi_interconnect_0_imp_xbar_0.xci
# IP: The module: 'myDesign_axi_interconnect_0_imp_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Xilinx/Projects/UART/UART.gen/sources_1/bd/myDesign/ip/myDesign_axi_interconnect_0_imp_xbar_0/myDesign_axi_interconnect_0_imp_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'myDesign_axi_interconnect_0_imp_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
